version: "3"
services:
  redis:
    build: redis/
    command: redis-server --protected-mode no
    ports:
      - 6379:6379
  php_server: 
    build:
      context: .
      dockerfile: php_server/Dockerfile
    command: php server.php
    links:
      - redis
    ports:
        - 8080:80
    depends_on:
      - redis
  php_client1: 
    build:
      context: .
      dockerfile: php_client1/Dockerfile
    command: php client1.php
    links:
        - redis
    ports:
        - 5000:5000
    depends_on:
        - redis
  php_client2:
    build:
      context: .
      dockerfile: php_client2/Dockerfile
    command: php client2.php
    links:
        - redis
    ports:
        - 5050:5050
    depends_on:
        - redis
